### ISSUE TITLE
Option to make SearchBox and DropdownSearch the same Widget

### ISSUE THREAD

**Issue by LuisEduardoSG** [salim-lachdhaf/dropdown_search#535] opened 2023-01-23 20:15 UTC
**Is your feature request related to a problem? Please describe.**
No, it isn't. But as of today, 01/23/2023, search box is a textfield inside of the dropdown's items list. In which, require of the user to make a second tap in order to start filtering/searching through items

**Describe the solution you'd like**
It could mean time saving and a more common approach on Mode.MENU of DropdownSearch, if the same field used to show the selected item, could be used to type and search/filter all items. 
 Maybe the image below help. Basically a typeable dropdown, which when focused user can either type to find a specific option or scroll to it.
![image](https://user-images.githubusercontent.com/30302350/214140380-e57680e9-5837-4773-9100-51b5c48692b5.png)

**Describe alternatives you've considered**
Set focus on searchbox right when items list is opened. But it just didn't seemed right.

**Comment by salim-lachdhaf** [comment] 2023-01-25 15:17
i'm still working time to time on this, for now the problem is when the dropdown request focus the menu get dismissed

**Comment by ronytesler** [comment] 2023-07-17 15:13
I'd also like to have that

**Comment by Arjun-Mahadev** [comment] 2023-10-16 17:01
Hey @salim-lachdhaf any update on this?

**Comment by steve3p0** [comment] 2024-04-26 12:54
This would be nice.

**Comment by salim-lachdhaf** [comment] 2024-09-10 20:47
This a nice feature , i tried to make it in the next version 6.0.0-pre but sadly i got no time to finish it, so it will be part of version 6.1.0 with adaptative widget feature

**Comment by salim-lachdhaf** [comment] 2024-12-07 23:16
Feature added in v7.0.0-pre. just use  `popupProps: PopupProps.autocomplete(...)`

**Closed by salim-lachdhaf** 2024-12-07 23:16 UTC
Labels: enhancement
