### ISSUE TITLE
Close popup issue

### ISSUE THREAD

**Issue by Tigran-Kosemyan** [salim-lachdhaf/dropdown_search#702] opened 2024-10-21 11:22 UTC
After update the latest version, use same logic with new changes, I get this error when dropdown opened and I go to another page , in previous version used same logic but I don't have this issue

The following assertion was thrown while finalizing the widget tree:
You have popped the last page off of the stack, there are no pages left to show
'package:go_router/src/delegate.dart':
Failed assertion: line 119 pos 7: 'currentConfiguration.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      GoRouterDelegate._debugAssertMatchListNotEmpty (package:go_router/src/delegate.dart:119:7)
#3      GoRouterDelegate._completeRouteMatch.<anonymous closure> (package:go_router/src/delegate.dart:165:7)
#4      GoRouterDelegate._completeRouteMatch (package:go_router/src/delegate.dart:167:6)
#5      GoRouterDelegate._handlePopPageWithRouteMatch (package:go_router/src/delegate.dart:135:7)
#6      _CustomNavigatorState._handlePopPage (package:go_router/src/builder.dart:416:42)
#7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5357:28)
#8      Navigator.pop (package:flutter/src/widgets/navigator.dart:2665:27)
#9      DropdownSearchPopupState.closePopup (package:dropdown_search/src/widgets/dropdown_search_popup.dart:781:34)
#10     DropdownSearchState.dispose (package:dropdown_search/dropdown_search.dart:773:34)
#11     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5826:11)
465 more
(elided 2 frames from class _AssertionError)

**Comment by salim-lachdhaf** [comment] 2024-10-21 13:19
Have you a reproducible simple code ? because from the log it seems there is an issue with your Navigation package.

**Comment by Tigran-Kosemyan** [comment] 2024-10-23 07:40
> Have you a reproducible simple code ? because from the log it seems there is an issue with your Navigation package.

I have StatefulNavigationShell and NavigationRail, using gorouter 

` void _goBranch(int index) {
    navigationShell.goBranch(
      index,
      initialLocation: true,
    );
  }`
  
After updating a package in my Flutter project, my app crashes under specific conditions. I have a parent screen that navigates to a second screen. In this second screen, I open a dropdown. When I click on the navigation rail to navigate to a different page (using initialLocation), the app crashes with an error.

Before updating the package, everything worked correctly. However, I need this update, and now the app crashes when navigating away from the second screen with an open dropdown.

**Comment by Tigran-Kosemyan** [comment] 2024-10-29 09:15
@salim-lachdhaf Hi Dear, any news?

**Comment by salim-lachdhaf** [comment] 2024-11-07 16:36
i'm not able to reproduce the issue, i think it's related to your routing implementation.

**Comment by MichaelNeufeld** [comment] 2024-11-14 09:25
I think I have the same problem. I have a DropdownSearch in dialog mode inside a statefull widget. when the widget rebuilds due to a setState from the onChange with the dialog open I get thrown back one page instead of the pop closing the dialog

**Comment by mhuete-iP** [comment] 2024-11-14 10:12
Hi, I have a similar issue and the PR #712 from @MichaelNeufeld also fixes it for me. @salim-lachdhaf could you please approve it?

I paste the exception I was getting here for reference:
 
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
setState() or markNeedsBuild() called when widget tree was locked.
This Overlay widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was:
  Overlay-[LabeledGlobalKey<OverlayState>#a2c44]

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3     throw_
errors.dart:296
packages/flutter/src/widgets/framework.dart 5179:9                              <fn>
framework.dart:5179
packages/flutter/src/widgets/framework.dart 5188:14                             markNeedsBuild
framework.dart:5188
packages/flutter/src/widgets/framework.dart 1223:5                              setState
framework.dart:1223
packages/flutter/src/widgets/overlay.dart 791:5                                 [_didChangeEntryOpacity]
overlay.dart:791
packages/flutter/src/widgets/overlay.dart 112:15                                set opaque
overlay.dart:112
packages/flutter/src/widgets/routes.dart 243:26                                 [_handleStatusChanged]
routes.dart:243
packages/flutter/src/animation/listener_helpers.dart 240:11                     notifyStatusListeners
listener_helpers.dart:240
packages/flutter/src/animation/animation_controller.dart 897:7                  [_checkStatusChanged]
animation_controller.dart:897
packages/flutter/src/animation/animation_controller.dart 828:5                  [_startSimulation]
animation_controller.dart:828
packages/flutter/src/animation/animation_controller.dart 695:12                 [_animateToInternal]
animation_controller.dart:695
packages/flutter/src/animation/animation_controller.dart 541:12                 reverse
animation_controller.dart:541
packages/flutter/src/widgets/routes.dart 307:5                                  didPop
routes.dart:307
packages/flutter/src/widgets/routes.dart 861:18                                 didPop
routes.dart:861
packages/go_router/src/delegate.dart 137:12                                     [_handlePopPageWithRouteMatch]
delegate.dart:137
packages/go_router/src/builder.dart 425:42                                      [_handlePopPage]
builder.dart:425
packages/flutter/src/widgets/navigator.dart 5357:18                             pop
navigator.dart:5357
packages/flutter/src/widgets/navigator.dart 2665:25                             pop
navigator.dart:2665
packages/dropdown_search/src/widgets/dropdown_search_popup.dart 781:34          closePopup
dropdown_search_popup.dart:781
packages/dropdown_search/dropdown_search.dart 773:34                            dispose
dropdown_search.dart:773
packages/flutter/src/widgets/framework.dart 5826:5                              unmount
framework.dart:5826
packages/flutter/src/widgets/framework.dart 2077:12                             [_unmount]
framework.dart:2077
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
framework.dart:2075
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
framework.dart:5669

**Comment by salim-lachdhaf** [comment] 2024-11-20 19:34
@verscph have you a reproducible example to analyse the issue ?
The PR has issues (regression) for now i cant accept it

**Comment by verscph** [comment] 2024-11-21 14:32
We're developing a Flutter Web app and this is the error we get without the fix of PR #712  : 

```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
setState() or markNeedsBuild() called when widget tree was locked.
This Overlay widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was:
  Overlay-[LabeledGlobalKey<OverlayState>#e91f0]

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3     throw_
packages/flutter/src/widgets/framework.dart 5179:9                              <fn>
packages/flutter/src/widgets/framework.dart 5188:14                             markNeedsBuild
packages/flutter/src/widgets/framework.dart 1223:5                              setState
packages/flutter/src/widgets/overlay.dart 791:5                                 [_didChangeEntryOpacity]
packages/flutter/src/widgets/overlay.dart 112:15                                set opaque
packages/flutter/src/widgets/routes.dart 243:26                                 [_handleStatusChanged]
packages/flutter/src/animation/listener_helpers.dart 240:11                     notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 897:7                  [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 828:5                  [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 695:12                 [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 541:12                 reverse
packages/flutter/src/widgets/routes.dart 307:5                                  didPop
packages/flutter/src/widgets/routes.dart 861:18                                 didPop
packages/flutter/src/widgets/navigator.dart 3167:16                             handlePop
packages/flutter/src/widgets/navigator.dart 4340:21                             [_flushHistoryUpdates]
packages/flutter/src/widgets/navigator.dart 5368:7                              pop
packages/flutter/src/widgets/navigator.dart 2665:25                             pop
packages/dropdown_search/src/widgets/dropdown_search_popup.dart 781:34          closePopup
packages/dropdown_search/dropdown_search.dart 773:34                            dispose
packages/flutter/src/widgets/framework.dart 5826:5                              unmount
packages/flutter/src/widgets/framework.dart 2077:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6886:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6998:9                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6998:9                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6998:9                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6886:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6886:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 6998:9                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
packages/flutter/src/widgets/framework.dart 2075:7                              <fn>
packages/flutter/src/widgets/framework.dart 5669:7                              visitChildren
packages/flutter/src/widgets/framework.dart 2073:12                             [_unmount]
dart-sdk/lib/internal/iterable.dart 49:7                                        forEach
packages/flutter/src/widgets/framework.dart 2086:15                             [_unmountAll]
packages/flutter/src/widgets/framework.dart 2954:7                              lockState
packages/flutter/src/widgets/framework.dart 3264:7                              finalizeTree
packages/flutter/src/widgets/binding.dart 1169:7                                drawFrame
packages/flutter/src/rendering/binding.dart 468:5                               [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1397:7                              [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1318:9                              handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1176:5                              [_handleDrawFrame]
dart-sdk/lib/async/zone.dart 1399:13                                            _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                            run
dart-sdk/lib/async/zone.dart 1209:7                                             runGuarded
lib/_engine/engine/platform_dispatcher.dart 1410:9                              invoke
lib/_engine/engine/platform_dispatcher.dart 310:5                               invokeOnDrawFrame
lib/_engine/engine/initialization.dart 187:36                                   <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 188:27  _callDartFunctionFast1

The AnimationController notifying status listeners was:
  AnimationController#832d4(◀ 1.000; for PageRouteBuilder<dynamic>)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by salim-lachdhaf** [comment] 2024-11-21 21:57
Could you tell me what kind of institutions you called on the `onChange` callback ?

**Comment by verscph** [comment] 2024-11-22 07:20
We call Future that saves a document in Firestore

**Comment by salim-lachdhaf** [comment] 2024-11-22 08:21
Are you calling something in relation with the `Navigator` ?

**Comment by verscph** [comment] 2024-11-22 14:27
Are you calling something in relation with the Navigator ? -> no

Another thing, do you use keys ? Like UniqueKey in your widget ? -> no

**Comment by salim-lachdhaf** [comment] 2024-11-22 14:42
could you share the content of the `onChange` please ?

**Comment by verscph** [comment] 2024-11-22 15:31
```
...
onChange: (TasksTemplate template) async => await viewModel.addTasksFromTemplate(template)
...
```

```
  Future<void> addTasksFromTemplate(TasksTemplate tasksTemplate) async {
    for (final phase in tasksTemplate.phases ?? []) {
      campaign!.addPhase(Phase.from(phase));
    }
    campaign!.editedBy = _appState.currentUser!.id!;
    campaign!.lastEdit = DateTime.now();
    await save();
  }

```

**Comment by verscph** [comment] 2024-11-22 22:24
Thanks for your opinion. I'll give you a bit more context:
- I've been using dropdown_search for years now
- we recently migrated from 3.0.1 to the latest version 6.0.1
- the code we call in onChange has not been changed during the upgrade, nor has the save function or state managemnt
- the dropdown_search implementation with 3.0.1 worked perfectly
- we don't pass keys explicitly to the widget
- the multiselect variant of 6.0.1 works fine in combination with the same state management, even when calling funtions that save the data to Firestore

Can you please explain why the issue appeared after the upgrade of dropdown_search and how we can resolve it?

**Comment by salim-lachdhaf** [comment] 2024-11-22 22:57
Sadly, without a reproducible example, I cannot help more.

Before version 6.0.0, we do not dismiss the popup before disposing the dropdown widget. This is an issue, as mentioned above and here: https://github.com/salim-lachdhaf/searchable_dropdown/issues/554.

Calling `closePopup` is a known behavior that exists in `DropdownButtonFormField`, for example - a widget developed by Flutter.

The only way I could reproduce exactly the same stack trace as yours is by assigning an explicit key (e.g., `UniqueKey()`) to the `DropdownSearch` widget and calling `setState` in the `onChange` callback. 

Single and multi selection are exactly the same  and should behave in the same way.

in your case, finding why `DropdownSearch` is disposed is the key of the solution.

you can fork the lib and remove this line `_popupStateKey.currentState?.closePopup()`  from `dispose` callback i'm pretty sure this will "HIDE" the issue, but the origin issue is still there `(DropdownSearch` get disposed)

**Comment by verscph** [comment] 2024-11-27 09:51
@salim-lachdhaf the use case is as follows:

- we show a list of campaigns based on a Firestore Stream
- one of the campaigns is updated by selecting a value from the DropdownSearch
- this update triggers the view to rebuild, as it shows the data provided by the campaigns Stream
- this rebuild results in https://github.com/salim-lachdhaf/dropdown_search/issues/702#issuecomment-2491384156

This worked before 6.0.0 and seems a "normal use" of Flutter/Firestore to me. Can you pls verify again?

**Comment by salim-lachdhaf** [comment] 2024-11-27 15:02
You have confirmed that your `DropdownSearch` does not have an explicit `UniqueKey` or a dynamic key.  

Therefore, one of the parent widgets of `DropdownSearch` likely has an explicit `UniqueKey` or a dynamic key.  
Check if any external packages being used are causing this issue.  

You can also list all the parent widgets of `DropdownSearch` to check them.

**Comment by VogelDevelopment** [comment] 2024-12-06 08:34
I enjoy using this library for quiet some time now as well, thanks for all the work! However as of the recent version stuff broke in my app too under a certain use-case.

Same problem on my side, I have a component in which I create the dropdown (pretty much a styled dropdown-field-component) and in one of my views I only want to show the dropdown in a dialog upon certain conditions, so I create the dropdown-field via showDialog and upon receiving the onChanged from the Dropdown I call pop for the context of the dialog (which contains my dropdown-field-component), as I want to pop the dialog of the dropdown-field-component and provide some value back with it. For me the onDismissed isn't firing either (and I can't find anything in the code-base in regards to it being fired), so I can also confirm that this is still an issue https://github.com/salim-lachdhaf/dropdown_search/issues/693.


Now in my function that notifies me when the selected option changes, I do the following: 
notifyParent: (dynamic newSelected) {
    this.compareSpecialDate = newSelected;
    ctx.pop(newSelected);
},

and doing that results in the error described here https://github.com/salim-lachdhaf/dropdown_search/issues/702#issuecomment-2475937652 , though I'm not using keys on these widgets atm. I can also confirm that there is no initState being re-triggered.

Now if I change the function to something like this: 
notifyParent: (dynamic newSelected) {
    this.compareSpecialDate = newSelected;
    if (ctx.mounted) {
         setState((){});
         if (ctx.canPop()) {
             Timer(Duration(milliseconds: 100), (){
                   ctx.pop(newSelected);
             });
        }
    }
},
everything works as expected. This however shouldn't be the solution, as waiting a set amount of time is just bad programming specially in this case. Using 50 milliseconds as timer results in it sometimes being too little, sometimes enough. Using postFrameCallback doesn't work at all in this case.


Here's my code showcasing what exactly I'm doing (SingleSelectDropdown is the styled field-component that will create a popup-dropdown by default):

`showDialog(
                            context: this.context,
                            builder: (BuildContext ctx) {
                              return StatefulBuilder(
                                builder: (context, setState) {
                                  return Dialog(
                                    child: SingleSelectDropdown(
                                      notifyParent: (dynamic newSelected) {
                                        this.compareSpecialDate = newSelected;
                                        if (ctx.mounted) {
                                          setState((){});
                                          if (ctx.canPop()) {
                                            Timer(Duration(milliseconds: 100), (){
                                              ctx.pop(newSelected);
                                            });
                                          }
                                        }
                                      },
                                      dropdownOptions: this.widget.params.specialDates.where((element) => element.id != this.specialDate.id).toList(),
                                      searchText: S.current.form_search_specialDate,
                                      initData: this.compareSpecialDate,
                                      primaryItemText: (dynamic data) => data.primaryInfoText(),
                                      secondaryItemText: (dynamic data) => data.secondaryInfoText(),
                                      idleText: S.current.select_specialDate,
                                    ),
                                  );
                                },
                              );
                            }).then((value) {`

and notifyParent is called like this in the DropdownSearch: 
`
              onChanged: (newValue) {
                if (this.mounted) {
                  setState(() {
                    if (newValue == null) {
                      this.dropdownValue = this.baseData;
                    } else {
                      this.dropdownValue = newValue;
                    }
                    this.widget.notifyParent(newValue);
                  });
                }
              },`


Hope this helps in some way to recreate the bug.

**Comment by salim-lachdhaf** [comment] 2024-12-06 09:25
@VogelDevelopment thank you for this details, i will take a look and keep you updated

**Comment by salim-lachdhaf** [comment] 2024-12-07 14:46
re open this issue if it's not solved in `v7.0.0-pre`.

**Closed by salim-lachdhaf** 2024-12-07 14:46 UTC

**Comment by verscph** [comment] 2024-12-07 15:50
Tx for confirming there's indeed an issue. Instead of changing the packages code, I solved it by
```  
Future<void> addTasksFromTemplate(TasksTemplate tasksTemplate) async {
    for (final phase in tasksTemplate.phases ?? []) {
      campaign!.addPhase(Phase.from(phase));
    }
    campaign!.editedBy = _appState.currentUser!.id!;
    campaign!.lastEdit = DateTime.now();
    // Workaround for issue with DropdownSearch and rebuild
    Future.delayed(const Duration(milliseconds: 200)).then((val) {
      save();
    });
  }
  ```
  
  Please add a comment to this issue when 7.0.0-pre is available

**Comment by verscph** [comment] 2024-12-08 08:14
@salim-lachdhaf 7.0.0-pre1 has breaking changes?

![Screenshot 2024-12-08 at 09 13 02](https://github.com/user-attachments/assets/d8bc3cf0-18b5-404c-93b0-02dda23337aa)

**Comment by salim-lachdhaf** [comment] 2024-12-08 08:32
https://github.com/salim-lachdhaf/dropdown_search/blob/master/CHANGELOG.md#breaking-changes

`PopupPropsMultiSelection` changed to `MultiSelectionPopupProps`

**Comment by VogelDevelopment** [comment] 2024-12-11 07:12
@salim-lachdhaf sorry we were on vacation - yes 7.0.0-pre1 has fixed the issue for me, now it works as expected again! Thanks a lot!
