### ISSUE TITLE
Ripple is affecting errorText and helperText, looks horrible with BorderRadius

### ISSUE THREAD

**Issue by Sinaloense** [salim-lachdhaf/dropdown_search#700] opened 2024-10-18 19:57 UTC
**Describe the bug**
Ripple is affecting errorText and helperText, looks horrible with BorderRadius

**To Reproduce**
1. Embed DropdownSearch with Material
2. Add borderRadius to clickProps
3. Add text to labelText or errorText
```
return Material(
      child: DropdownSearch<String>(
        items: (filter, infiniteScrollProps) => ['hello', 'world'],
        clickProps: ClickProps(
          borderRadius: BorderRadius.circular(20.00),
        ),
        decoratorProps: DropDownDecoratorProps(
          decoration: InputDecoration(
            labelText: "Sucursal",
            helperText: 'Busque y seleccione la sucursal',
            // errorText: 'Error',
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(20.00),
            ),
          ),
        ),
      ),
    );
```

**Expected behavior**
Add an option to disable ripple effect to labelText and errorText.

**Screenshots**
![flutter_pos_tFnGviksBG](https://github.com/user-attachments/assets/581cdaf8-fbcc-4444-8abc-1e8a64aa9b33)
![flutter_pos_Li8vPW9OAp](https://github.com/user-attachments/assets/32a4fd82-ed9c-4095-a80f-cc9a07754567)

I dont know if this issue is related with: https://github.com/salim-lachdhaf/dropdown_search/pull/660

dropdown_search: ^6.0.1

**Comment by salim-lachdhaf** [comment] 2024-10-18 20:53
Sadly it's a known issue https://github.com/flutter/flutter/issues/106659

**Comment by salim-lachdhaf** [comment] 2024-10-18 22:21
The only solution to the issue is to rewrite the inputDecorator and make it clickable from inside , not as child of inkWell.

**Comment by salim-lachdhaf** [comment] 2024-12-07 12:17
i will close this issue because it's related to Flutter framework and not to package directly.

if you do not intersted to the splash, use as @vasilich6107 mentioned

**Closed by salim-lachdhaf** 2024-12-07 12:17 UTC

**Comment by salim-lachdhaf** [comment] 2025-08-22 13:21
you can use `clickProps `property like this:

```
DropdownSearch<int>(
           clickProps: ClickProps(
              canRequestFocus: false,
              focusColor: Colors.transparent,
              splashColor: Colors.transparent,
              mouseCursor: WidgetStateMouseCursor.textable,
              highlightColor: Colors.transparent,
              hoverColor: Colors.transparent,
           ),
          items: (f, cs) => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
),
```
